service: poc-api1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
          Resource:
            - arn:aws:s3:::poc-api1-dev-serverlessdeploymentbucket-x2kvmmin1ppi/*
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - arn:aws:dynamodb:sa-east-1:816925220115:table/Users
functions:
  api:
    handler: src/app.app
    events:
      - httpApi: "*"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
